### ISSUE TITLE
Few issues like Variable missing, resize code and missing region

### ISSUE THREAD

**Issue by rcgopi100** [spaceml-org/Missing-Pixel-Filler#2]
Hi,
I have run your code on Google Colab and found few things for you to note.
https://colab.research.google.com/drive/1dD0yJKb159io4ZS_LsUCZ8IHGwMrKlPA?usp=sharing
Check the blog - https://www.gopichandrakesan.com/day-96-facing-image-region-missing-on-your-photo-lets-check-the-image-on-missing-pixel-filler/

1. Code is getting img variable missing and I fixed the code.

2. The image requires the same dimension on all sides if you are uploading a different size then I am getting an error "valueError: 3. empty range for randrange() (621,224, -397)... E-g 224 x 224 size would be better and you need to add a code to resize it.
3. The code is considering the good region as a missing region on the image.  You can check the 1st image.

**Comment by sidgan** [comment]
Thank you @rcgopi100  for raising these issues, and for testing it out in your blog! Would you like to send in a PR for the first issue? The team will look into 2 and 3. Thank you!

**Comment by sarahchen6** [comment]
Hi @rcgopi100, we will work on fixing these issues! Thank you again for helping test our code and noting these problems!

**Comment by sarahchen6** [comment]
Addressed issues 1 and 3 by adjusting our code (issue 3 was a problem because our original code was replacing all black pixels) and corrected issue 2 by adding swath gap size dimension arguments to the filler functions. Thanks again for bringing these to our attention and for your patience!
